### ISSUE TITLE
finalQuery.match is not a function

### ISSUE THREAD

**Issue by abood1tameme1** [Tomato6966/erela.js#33]
at Spotify.<anonymous> (F:\\\node_modules\erela.js-spotify\dist\plugin.js:79:51)
    at Generator.next (<anonymous>)
    at F:\\\node_modules\erela.js-spotify\dist\plugin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (F:\\\node_modules\erela.js-spotify\dist\plugin.js:4:12)

**Comment by NedcloarBR** [comment]
Hello! 
I recommend you not to use this plugin because it is kind of old and outdated from a look at the plugins for [Lavalink](https://github.com/lavalink-devs/Lavalink/blob/master/PLUGINS.md)
I'm using the [LavaSrc](https://github.com/topi314/LavaSrc) for Spotify tracks
